# Generated by Django 4.2.16 on 2024-11-15 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10)),
                ('guia_despacho', models.CharField(max_length=50)),
                ('encargado_recepcion', models.CharField(max_length=100)),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('kilometraje_salida', models.IntegerField()),
                ('kilometraje_llegada', models.IntegerField(blank=True, null=True)),
                ('destino', models.CharField(max_length=200)),
                ('numero_personas', models.IntegerField()),
                ('hora_salida', models.DateTimeField(auto_now_add=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('motivo_visita', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
