# Generated by Django 4.2.16 on 2024-11-17 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitante",
            options={"ordering": ["-hora_entrada"]},
        ),
        migrations.RemoveField(
            model_name="visitante",
            name="hora_ingreso",
        ),
        migrations.AddField(
            model_name="visitante",
            name="hora_entrada",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visitante",
            name="motivo_visita",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="visitante",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visitante",
            name="run",
            field=models.CharField(max_length=12),
        ),
    ]
