# Generated by Django 4.2.16 on 2024-12-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_visitante_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="run",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="matricula",
            field=models.CharField(max_length=10),
        ),
    ]
