# Generated by Django 4.2.16 on 2024-12-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_proveedor_run_alter_vehiculo_matricula"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditoriaAccion",
        ),
    ]
